builds:
  -
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    ldflags: -s -w -X main.version={{.Version}}

archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

#changelog:
#  sort: asc
#  filters:
#    exclude:
#    - '^docs:'
#    - '^test:'
