version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/bgetsug/tt
    steps:
      - checkout
      - run:
          name: GoReleaser
          command: curl -sL https://git.io/goreleaser | bash